services:
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "alembic upgrade head && flask run --host=0.0.0.0 --port=8000"
    env_file:
      - .env


  database:
    image: 'postgres'
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "FlaskUser", "-d", "FlaskDatabase"]
      interval: 5s
      timeout: 3s
      retries: 5  

volumes:
  postgres_data: